### PR TITLE
FIX Redirect to back URL after login (fixes #79)

### LINKED ISSUE #79: BackURL is ignored
Hi team,

when sending a request with a BackURL e.g. https://www.mydomain.co.nz/Security/login/RealMe?BackURL=/dashboard/, I expect to be redirected to https://www.mydomain.co.nz/dashboard/ when I login successfully as I would if I was using the stock authentication.

The reason is that when the request is made, the BackURL is not stored in the session var RealMeBackURL.

Is this a bug?

Cheers

Andy

### PR DESCRIPTION
**Pull request by andreaspiening**
Not really sure about the merge target, please advise.

### CODE REVIEW

File: src/RealMeService.php [hunk 1]
```diff
@@ -48,9 +48,9 @@ class RealMeService implements TemplateGlobalProvider
     const AUTHN_LOW_STRENGTH = 'urn:nzl:govt:ict:stds:authn:deployment:GLS:SAML:2.0:ac:classes:LowStrength';
     const AUTHN_MOD_STRENTH = 'urn:nzl:govt:ict:stds:authn:deployment:GLS:SAML:2.0:ac:classes:ModStrength';
     const AUTHN_MOD_MOBILE_SMS =
-        'urn:nzl:govt:ict:stds:authn:deployment:GLS:SAML:2.0:ac:classes:ModStrength::OTP:Mobile:SMS';
+    'urn:nzl:govt:ict:stds:authn:deployment:GLS:SAML:2.0:ac:classes:ModStrength::OTP:Mobile:SMS';
```
Comment (michalkleiner) [inline src/RealMeService.php]: please reset the change to this line

File: src/RealMeService.php [hunk 2]
```diff
@@ -48,9 +48,9 @@ class RealMeService implements TemplateGlobalProvider
...
     const AUTHN_MOD_TOKEN_SID =
-        'urn:nzl:govt:ict:stds:authn:deployment:GLS:SAML:2.0:ac:classes:ModStrength::OTP:Token:SID';
+    'urn:nzl:govt:ict:stds:authn:deployment:GLS:SAML:2.0:ac:classes:ModStrength::OTP:Token:SID';
```
Comment (michalkleiner) [inline src/RealMeService.php]: please reset the change to this line

File: src/RealMeService.php [hunk 3]
```diff
@@ -816,7 +821,7 @@ public function getMetadataOrganisationDisplayName()
     public function getMetadataOrganisationUrl()
     {
         $url = $this->config()->metadata_organisation_url;
-        return (strlen($url) > 0) ? $url: null;
+        return (strlen($url) > 0) ? $url : null;
```
Comment (michalkleiner) [inline src/RealMeService.php]: please reset the change to this line

File: src/RealMeService.php [hunk 4]
```diff
@@ -636,6 +637,10 @@ public function getBackURL(HTTPRequest $request)
         if ($session->get('RealMeBackURL')) {
             $url = $session->get('RealMeBackURL');
             $session->clear('RealMeBackURL'); // Ensure we don't redirect back to the same error twice
+        } elseif ($request->requestVar('BackURL')) {
+            $url = $request->requestVar('BackURL');
+        } elseif ($request->postVar('RelayState')) {
```
Comment (michalkleiner) [inline src/RealMeService.php:649]: Is this needed to solve your issue? Or just trying to cover more ground?

**Comment by michalkleiner** [comment]
Thanks @andreaspiening, a few minor inline comments. I think targeting `4` is fine here as an enhancement to the current set of redirect-back options, rather than fixing something broken which could possibly target `4.1`.

What's your view @maxime-rainville?

File: src/RealMeService.php (hunk 4 above)
Comment (andreaspiening) [reply src/RealMeService.php:649]: Yes, this is called in a number of different contexts.

**Comment by andreaspiening** [comment]
> Thanks @andreaspiening, a few minor inline comments. I think targeting `4` is fine here as an enhancement to the current set of redirect-back options, rather than fixing something broken which could possibly target `4.1`.
> 
> What's your view @maxime-rainville?

Thanks 

> Thanks @andreaspiening, a few minor inline comments. I think targeting `4` is fine here as an enhancement to the current set of redirect-back options, rather than fixing something broken which could possibly target `4.1`.
> 
> What's your view @maxime-rainville?

Thanks @michalkleiner, imho this is a bug:
You request a resource that requires authentication (e.g. ./admin) > you get redirected in order to authenticate (e.g. ./Security/login?BackURL=/admin) > you authenticate > you land on the homepage (e.g. ./) but you should see the requested resource (here: ./admin).

This is not an alternative option to using RealMeBackURL, RealMeBackURL is currently not doing anything either. Afaik if you are using RealMe there is currently no way to be redirected to where you wanted to go. This patch fixes both options.

**Comment by andreaspiening** [comment]
Hi @michalkleiner, Looking at the new title you set for this patch, I think there is a misunderstanding: I'd be happy to use `RealMeBackURL` instead of `BackURL`, but currently neither is working.

If you look at the code, there is only one place where `RealMeBackURL` is set: `RealmeService::enforceLogin(HTTPRequest $request, $backUrl = null)`, which has the optional `$backURL`. Now if you look for all places where `enforceLogin()` is used, you will find, that the `$backURL` is never passed. That is in line with my problem: `RealMeBackURL` doesn't work out of the box.

**Comment by michalkleiner** [comment]
Thanks for clarifying that, @andreaspiening.

Might be circling around, but if `RealMeBackURL` worked as expected, would that sort your problem?
I just basically don't want to put in a workaround instead of fixing the underlying issue (if there's one closer to the inner workings of the module).

**Comment by andreaspiening** [comment]
Hi @michalkleiner, if RealMeBackURL was working, it would solve my problem. I just need any way to redirect after using realme.

I think my fix is not a work around, but it is fixing the underlying issue. It also fixes both RealMeBackURL and - more importantly - BackURL. By using RealMeBackURL with BackURL and then the ReamMe supplied RelayState POST var as fallbacks it gracefully degrades.

RealMeBackURL does not tie into the authentication redirect process (see my example above: `./Security/login?BackURL=admin`) and imo should be considered an alternative to the main BackURL. BackURL should be considered the standard, as it is the query parameter that is used throughout the rest of the framework.

**Review by michalkleiner — APPROVED** [review]

**Comment by michalkleiner** [comment]
I'm reasonably happy with the change, but would prefer a counter-sign from @madmatt or @emteknetnz as any changes to this module can have a bigger impact than others.

**Comment by emteknetnz** [comment]
I'm not particularly familiar with realme

I did notice this which seems a little odd

We `$session->clear('RealMeBackURL');`, then immediately set it again with `$request->getSession()->set('RealMeBackURL', $backURL);`.

There's a comment `// Ensure we don't redirect back to the same error twice` ... I'm just wondering if we're going to end up doing what that comment says we don't want to do

**LoginHandler**
```
class LoginHandler extends RequestHandler
{
    public function login(HTTPRequest $request)
    {
        if ($backURL = $this->service->getBackURL($request)) {
            $request->getSession()->set('RealMeBackURL', $backURL);
        }
```

**RealMeService**        
```
class RealMeService implements TemplateGlobalProvider
{
    public function getBackURL(HTTPRequest $request)
    {
        $url = null;
        $session = $request->getSession();

        if ($session->get('RealMeBackURL')) {
            $url = $session->get('RealMeBackURL');
            $session->clear('RealMeBackURL'); // Ensure we don't redirect back to the same error twice
```

**Comment by andreaspiening** [comment]
Thanks @emteknetnz,

RealmeService::getBackURL() is used in a number of places. When we set the RealMeBackURL in the login handler, we're about to render the realme button. The backURL is not retrieved from the session (because enforceLogin hasn't been called yet), but from the request, because we are preparing to redirect to realme. So the clearing doesn't actually happen and the storing of the backurl in the session has to happen, in order for it to be available upon return to the acs.

Can you explain, how we can end up redirecting multiple times?

It's not like I haven't tested it. The fix is working. I m afraid you either have to take my word or try it out yourself ;)

File: src/RealMeService.php [hunk 5]
```diff
@@ -480,7 +480,8 @@ public function enforceLogin(HTTPRequest $request, $backUrl = null)
             Member::singleton()->extend("onRealMeLoginFailure", $e);
 
             // No auth data or failed to decrypt, enforce login again
-            $this->getAuth()->login(Director::absoluteBaseURL());
+            $validBackURL = $this->validSiteURL($backUrl ?: $this->getBackURL($request));
```
Comment (emteknetnz) [inline src/RealMeService.php]: The use of  `?:` here is a bit messy, would be cleaner to change the `if ($backUrl)` block above  in this file to have an `else { $backUrl = $this->getBackURL($request) }`
Below that if/else then do the `$this->validateSiteURL()` check and fallback to `Director::absoluteBaseURL()`

File: src/Authenticator/LoginHandler.php [hunk 6]
```diff
@@ -77,8 +77,12 @@ public function link($action = null)
      *
      * @return array
      */
-    public function login()
+    public function login(HTTPRequest $request)
     {
+        if ($backURL = $this->service->getBackURL($request)) {
```
Comment (emteknetnz) [inline src/Authenticator/LoginHandler.php:82]: Can we move all of this to `RealMeSerive.php`?

**Review by emteknetnz — CHANGES_REQUESTED** [review]
Some opportunities to clean the code up a little

File: src/Authenticator/LoginHandler.php (hunk 6 above)
Comment (andreaspiening) [reply src/Authenticator/LoginHandler.php:82]: This is a request handler. It is supposed to handle requests. Can you be a bit more specific please? Why does it have to be moved, which bits and where in RealmeService?

**Comment by madmatt** [comment]
This looks good to me once you've made the last change @emteknetnz requested, thanks @andreaspiening for your work on this!

Have you checked the SameSite attribute? I have a sneaking suspicion that the reason the back URL isn't working for you is that you're getting a different session because the session cookie doesn't have SameSite=Lax set, meaning that the POST back from RealMe to the ACS endpoint happens without the cookie, however that could be a total red herring.

Either way, this works for me - the only other alternative is to use the RelayState portion of the URL to do this, however RealMe has quite a restrictive length on the RelayState, something like 100 characters or something? So realistically you could only do that if you somehow encoded it (or used RelayState to encode the session identifier or similar).

If this approach works for you, that seems good to me. A final super minor thought is if it makes sense, could you update the documentation with the suggested (and working) way to set the back URL successfully? Not a blocker for merge, we can tidy it up later.

Thanks everyone!

**Review by andreaspiening — COMMENTED** [review]
I moved the backURL condition to the top. Could you please have another look? Cheers

**Comment by andreaspiening** [comment]
> This looks good to me once you've made the last change @emteknetnz requested, thanks @andreaspiening for your work on this!
> 
> Have you checked the SameSite attribute? I have a sneaking suspicion that the reason the back URL isn't working for you is that you're getting a different session because the session cookie doesn't have SameSite=Lax set, meaning that the POST back from RealMe to the ACS endpoint happens without the cookie, however that could be a total red herring.
> 
> Either way, this works for me - the only other alternative is to use the RelayState portion of the URL to do this, however RealMe has quite a restrictive length on the RelayState, something like 100 characters or something? So realistically you could only do that if you somehow encoded it (or used RelayState to encode the session identifier or similar).
> 
> If this approach works for you, that seems good to me. A final super minor thought is if it makes sense, could you update the documentation with the suggested (and working) way to set the back URL successfully? Not a blocker for merge, we can tidy it up later.
> 
> Thanks everyone!

Thanks @madmatt,

SameSite is covered by running the backURL through RealmeService::validSiteURL() on line 456.

Cheers

Andy

**Comment by andreaspiening** [comment]
Sorry, forgot to mention: the patch also sets the correct RelayState.

**Comment by andreaspiening** [comment]
Sorry again for the piecemeal. Regarding the documentation: with the patch in place, there's nothing users have to do anymore, because the framework adds the correct query parameter to the login handler request automatically, only now it works.

File: src/Authenticator/LoginHandler.php (hunk 6 above)
Comment (emteknetnz) [reply src/Authenticator/LoginHandler.php:82]: OK makes sense, reading the docblock for enforceLogin(), I can see what you've added this here

```
     * Enforce login via RealMe. This can be used in controllers to force users to be authenticated via RealMe (not
     * necessarily logged in as a {@link Member}), in the form of:
     * <code>
     * Session::set('RealMeBackURL', '/path/to/the/controller/method');
     * if($service->enforceLogin()) {
```

**Review by emteknetnz — APPROVED** [review]

**Comment by andreaspiening** [comment]
Thanks everybody. I appreciate the time and effort. One last favor: could you please create a release?

**Comment by emteknetnz** [comment]
@andreaspiening As this would require a minor release rather than a patch release, unfortunately no.  We'll be doing a quarterly minor beta release (CMS 4.10 beta1) this week which will include a beta1 release for realme.  In a months time we'll do an rc1 release, and in 2 months a stable

I've re-cut the 4.2 branch (which 4.2.0-beta1 will use) that now includes this pull-request, so I'd recommend that you use

`"silverstripe/realme": "4.2.x-dev#cd402eff8701a476904c293aefac07f6f52b52c0 as 4.2.0"` in the meantime

Please note that 4.2 includes a requirement for "silverstripe/framework": "^4.10" which is unreleased which is required for phpunit9 support

The will probably make it hard/impossible to actually install, unless you're comfortable installing framework 4.x-dev.  You could work around this with adding this in your composer.json (untested, though the something close to this will work, main thing is changing the silverstripe/framework requirement from ^4.10 to *)

```
"repositories": [
  {
    "type": "package",
    "package": {
      "name": "silverstripe/realme",
      "type": "silverstripe-vendormodule",
      "minimum-stability": "dev",
      "require": {
          "php": "^7.3 || ^8.0",
          "silverstripe/framework": "*",
          "onelogin/php-saml": "^3"
      },
      "dist": {
          "url": "https://github.com/silverstripe/silverstripe-realme/archive/cd402eff8701a476904c293aefac07f6f52b52c0.zip",
          "type": "zip"
      },
      "extra": {
          "expose": [
              "client/javascript",
              "client/css",
              "client/images"
          ]
      },
      "autoload": {
          "psr-4": {
              "SilverStripe\\RealMe\\": "src/",
              "SilverStripe\\RealMe\\Tests\\": "tests/"
          }
      }
    }
  },
]
```

It's a bit convoluted though. You might just be better off just using your fork for now.

**Comment by michalkleiner** [comment]
I'd be happy to backport the fix to 4.1 and release 4.1.4.

**Comment by emteknetnz** [comment]
@michalkleiner issue with that is there's an API addition so we can't do that, it would be a semver violation

**Comment by michalkleiner** [comment]
@emteknetnz even if we made the `$request` param (and the logic using it) optional?

**Comment by emteknetnz** [comment]
It's an API addition causing a signature change so it needs to be released as a minor

Semver can be pretty restrictive and in this instance you could easily make a case that it makes no practical difference.  However blind adherence to it does simplify things as it saves endless discussions of "how much do we allow"
